[package]
name = "workflow-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
workflow = { path = "../workflow", features = ["full"] }

[package.metadata.component]
package = "component:workflow"
